"""
Storage for the AI backtest ledger — verdicts generated on reconstructed
historical dates (core/point_in_time.py), kept in `ai_calls_backtest`,
deliberately separate from the live `ai_calls` table.

Why separate: `ai_calls` is marketed as an honest, unedited record of real
usage — "we log every call we make." Backtest verdicts are real Claude
output but on a synthetic historical prompt, generated by a script rather
than a user asking a question. Writing them to the same table would make
that marketing claim false the moment anyone checked the row count. This
table exists to answer a different, equally legitimate question — "how
good are these verdicts, validated against much more history than real
usage alone could ever produce" — and is presented that way, never merged
into the live ledger.

Resolution reuses core.track_record's price-lookup and return/alpha
calculation as-is: a backtest call is just a call whose date happens to
already be in the past, so every horizon typically resolves on first read
instead of waiting weeks.
"""

from __future__ import annotations

import logging
from datetime import date, datetime, timezone
from typing import Any

from core.track_record import HORIZONS, _resolve_row

_log = logging.getLogger("stockbrook")

_DUPLICATE_KEY = "23505"


def _supabase():
    try:
        from core.db import get_client
        return get_client()
    except Exception:
        return None


_REQUIRED_COLUMNS = ("criteria_passed", "unsourced_numbers",
                     "response_text", "universe_tier",
                     "return_30d", "alpha_30d", "return_90d", "alpha_90d",
                     "return_180d", "alpha_180d",
                     "resolved_at", "resolve_attempts")


def schema_ready() -> bool:
    """Does the table have every column log_backtest_call writes?

    Run before a batch spends anything. A missing column doesn't fail
    until the insert, AFTER the Claude call it was meant to record has
    already been paid for — a whole scheduled run could be spent that way
    with nothing to show for it."""
    sb = _supabase()
    if not sb:
        return False
    try:
        sb.table("ai_calls_backtest").select(",".join(_REQUIRED_COLUMNS)).limit(1).execute()
        return True
    except Exception:
        _log.exception("ai_calls_backtest schema check failed")
        return False


def already_tried(symbol: str, action: str, call_date: date) -> bool:
    """Has this exact (symbol, action, date) combination already been
    generated? Checked before spending an API call, not relied on as the
    only guard — the table's own unique constraint is the real backstop."""
    sb = _supabase()
    if not sb:
        return False
    try:
        res = (sb.table("ai_calls_backtest").select("id")
               .eq("symbol", symbol.upper()).eq("action", action)
               .eq("call_date", call_date.isoformat()).limit(1).execute())
        return bool(res.data)
    except Exception:
        _log.exception("ai_calls_backtest existence check failed for %s %s %s",
                       symbol, action, call_date)
        return False


def log_backtest_call(symbol: str, action: str, decision: str,
                      price_at_call: float | None, spy_at_call: float | None,
                      rules_met: int | None, rules_total: int | None,
                      call_date: date, data_gaps: list[str],
                      filing_form: str | None = None,
                      filing_date: str | None = None,
                      criteria_passed: bool | None = None,
                      unsourced: list[str] | None = None,
                      response_text: str | None = None,
                      universe_tier: str | None = None) -> bool:
    """Insert one backtest verdict. Returns True on success, False on a
    genuine failure (duplicates are treated as success — the row already
    exists, which is the desired end state either way)."""
    sb = _supabase()
    if not sb:
        _log.error("ai_calls_backtest insert skipped: no Supabase client "
                   "(set SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY)")
        return False
    row = {
        "symbol": symbol.upper(), "action": action, "decision": decision,
        "price_at_call": price_at_call, "spy_at_call": spy_at_call,
        "rules_met": rules_met, "rules_total": rules_total,
        "call_date": call_date.isoformat(), "data_gaps": data_gaps,
        "filing_form": filing_form, "filing_date": filing_date,
        "criteria_passed": criteria_passed,
        # None stays None: that's "not audited", which the faithfulness
        # rate must exclude rather than count as a clean result. An empty
        # list is the different, stronger claim that it WAS audited and
        # nothing was flagged.
        "unsourced_numbers": unsourced,
        # Kept so a flagged number can be read in context later. Without
        # the model's own words, "unsourced" can't be told apart from
        # honest arithmetic after the fact.
        "response_text": response_text,
        "universe_tier": universe_tier,
    }
    try:
        sb.table("ai_calls_backtest").insert(row).execute()
        return True
    except Exception as exc:
        if getattr(exc, "code", None) == _DUPLICATE_KEY:
            return True
        _log.exception("ai_calls_backtest insert failed for %s %s %s",
                       symbol, action, call_date)
        return False


def _all_backtest_calls() -> list[dict]:
    sb = _supabase()
    if not sb:
        return []
    # Paged, not one .limit(): Supabase caps a single response at 1,000 rows
    # regardless of the limit asked for, so a lone request silently returns
    # the newest 1,000 and every total computed from it stops growing.
    rows: list[dict] = []
    page = 1000
    try:
        while True:
            res = (sb.table("ai_calls_backtest").select("*")
                   .order("id", desc=True)
                   .range(len(rows), len(rows) + page - 1).execute())
            batch = res.data or []
            rows.extend(batch)
            if len(batch) < page:
                return rows
    except Exception:
        # Not the pages read so far — a partial set is exactly the silent
        # undercount the paging exists to prevent.
        _log.exception("ai_calls_backtest read failed")
        return []


_RESOLVED_FIELDS = tuple(f"{k}_{h}" for h in HORIZONS for k in ("return", "alpha"))

# A symbol that no longer prices (delisted, renamed) will never resolve.
# Without a cap it would be refetched on every pass, forever.
_MAX_RESOLVE_ATTEMPTS = 3

# Kept out of the headline summary: a survivorship-biased slice that would
# quietly drag the default numbers. Still reported under by_tier.
_EXCLUDED_FROM_DEFAULT = ("legacy30",)


def _stored_resolution(row: dict) -> dict:
    """The row with its STORED return/alpha fields promoted, no network.

    Keys are only present when non-null, matching what _resolve_row
    produces, so _score's "is this horizon resolved" check is unchanged.
    """
    out = {k: v for k, v in row.items() if k not in _RESOLVED_FIELDS}
    for field in _RESOLVED_FIELDS:
        value = row.get(field)
        if value is not None:
            out[field] = float(value)
    return out


def resolve_unresolved(limit: int = 200) -> tuple[int, int]:
    """Compute and persist outcomes for rows that don't have them yet.

    Returns (resolved, attempted). Called at the end of a worker run so
    the backlog drains a batch at a time rather than being recomputed on
    every read — historical prices don't change, so this is done once per
    call and then never again.
    """
    sb = _supabase()
    if not sb:
        return (0, 0)
    try:
        rows = (sb.table("ai_calls_backtest").select("*")
                .is_("resolved_at", "null")
                .lt("resolve_attempts", _MAX_RESOLVE_ATTEMPTS)
                .order("id").limit(limit).execute()).data or []
    except Exception:
        _log.exception("ai_calls_backtest unresolved fetch failed")
        return (0, 0)

    resolved_count = 0
    for row in rows:
        try:
            filled = _resolve_row(row)
        except Exception:
            _log.exception("resolution failed for id=%s", row.get("id"))
            filled = {}
        patch: dict[str, Any] = {f: filled.get(f) for f in _RESOLVED_FIELDS}
        patch["resolve_attempts"] = (row.get("resolve_attempts") or 0) + 1
        # Only call it resolved once something actually came back. A
        # transient fetch failure would otherwise freeze nulls in place
        # as though they were the real answer.
        if any(patch[f] is not None for f in _RESOLVED_FIELDS):
            patch["resolved_at"] = datetime.now(timezone.utc).isoformat()
            resolved_count += 1
        try:
            sb.table("ai_calls_backtest").update(patch).eq("id", row["id"]).execute()
        except Exception:
            _log.exception("resolution write failed for id=%s", row.get("id"))
    return (resolved_count, len(rows))


def _score(rows: list[dict], action: str, label: str) -> dict:
    """Win rate / return / alpha for one set of already-resolved calls.

    Both returns and alpha are reported in the DIRECTION THE CALL IMPLIED,
    not as the raw stock move: for a sell, a stock that fell is a win, so
    its sign is flipped here. The raw per-row `return_*`/`alpha_*` fields
    stay factual (what the stock actually did) — this is the only place
    that reorients them, because an aggregate labelled "avg alpha" is
    read as "how well did the calls do", and an unflipped sell average
    says the exact opposite of what a reader assumes.
    """
    rows = [r for r in rows if f"return_{label}" in r]
    if not rows:
        return {"count": 0, "avg_return": None, "win_rate": None,
                "avg_alpha_vs_spy": None}
    sign = 1 if action == "buy" else -1
    rets = [sign * r[f"return_{label}"] for r in rows]
    alphas = [sign * r[f"alpha_{label}"] for r in rows if f"alpha_{label}" in r]
    wins = sum(1 for r in rets if r > 0)
    return {
        "count": len(rets),
        "avg_return": round(sum(rets) / len(rets), 4),
        "win_rate": round(wins / len(rets), 4),
        "avg_alpha_vs_spy": round(sum(alphas) / len(alphas), 4) if alphas else None,
    }


def _summarize(resolved: list[dict]) -> dict[str, Any]:
    ai_yes = [r for r in resolved if r.get("decision") == "YES"]
    rules_passed = [r for r in resolved if r.get("criteria_passed") is True]
    summary: dict[str, Any] = {}
    for label in HORIZONS:
        for action in ("buy", "sell"):
            def by_action(rows: list[dict]) -> list[dict]:
                return [r for r in rows if r["action"] == action]
            summary[f"{action}_{label}"] = {
                "ai_yes": _score(by_action(ai_yes), action, label),
                "rules_passed": _score(by_action(rules_passed), action, label),
                "all_calls": _score(by_action(resolved), action, label),
            }
    return summary


def compute_backtest_record() -> dict:
    """Scored backtest results, as three arms that only mean something
    side by side.

      ai_yes        — calls where Claude said YES
      rules_passed  — calls where the deterministic criteria passed,
                      whatever Claude then said
      all_calls     — every call sampled, the base rate

    The third arm is what makes the other two readable. Equities drift
    up, so on a long horizon a "sell" that never fires looks brilliant
    and one that always fires looks terrible, with no skill involved
    either way. A win rate is only interpretable as the distance between
    an arm and that base rate — and the AI is only earning its cost if
    ai_yes beats rules_passed, since the rules run for free.

    `summary` covers the CURRENT sampling design and deliberately leaves
    out "legacy30" — the first ~800 calls, drawn from a fixed list of 30
    mega-caps. Those names are large today because they rose, which drags
    every sell result down: including them moved the headline 180-day
    figure from 41% to 32%. A reader reaching for the obvious key should
    not land on a sample already known to be biased, so legacy30 stays
    available under `by_tier`, labelled, rather than blended into the
    default.

    The exclusion is a denylist, not an allowlist: any tier added later
    counts toward `summary` automatically. An allowlist would silently
    drop a new tier from the headline and nobody would notice.
    """
    all_rows = _all_backtest_calls()
    # Stored outcomes only — no price fetching. Re-resolving every row on
    # each read had grown to seven minutes as the universe widened, which
    # no API endpoint could serve. Rows still awaiting resolution are
    # reported below rather than silently dropped.
    resolved = [_stored_resolution(c) for c in all_rows]

    default_rows = [r for r in resolved
                    if (r.get("universe_tier") or "unknown") not in _EXCLUDED_FROM_DEFAULT]
    tiers = sorted({r.get("universe_tier") or "unknown" for r in resolved})
    by_tier = {
        t: {
            "calls": sum(1 for r in resolved if (r.get("universe_tier") or "unknown") == t),
            "summary": _summarize([r for r in resolved
                                   if (r.get("universe_tier") or "unknown") == t]),
        }
        for t in tiers
    }

    # Rows written before criteria_passed/unsourced_numbers existed carry
    # NULLs; the comparison arms are only as big as the rows that have them.
    with_baseline = sum(1 for r in all_rows if r.get("criteria_passed") is not None)
    audited = [r for r in all_rows if r.get("unsourced_numbers") is not None]
    flagged = [r for r in audited if r.get("unsourced_numbers")]

    return {
        "summary": _summarize(default_rows),
        "summary_calls": len(default_rows),
        "summary_excludes": list(_EXCLUDED_FROM_DEFAULT),
        "by_tier": by_tier,
        "total_backtest_calls": len(all_rows),
        "ai_yes_calls": sum(1 for r in resolved if r.get("decision") == "YES"),
        "rows_with_baseline": with_baseline,
        "unresolved_calls": sum(1 for r in all_rows if r.get("resolved_at") is None),
        "faithfulness": {
            "audited": len(audited),
            "with_unsourced_numbers": len(flagged),
            "rate": round(len(flagged) / len(audited), 4) if audited else None,
        },
        "is_backtest": True,  # every consumer of this dict must label it as such
        "recent_calls": resolved[:60],
    }
