"""
Storage for the AI backtest ledger — verdicts generated on reconstructed
historical dates (core/point_in_time.py), kept in `ai_calls_backtest`,
deliberately separate from the live `ai_calls` table.

Why separate: `ai_calls` is marketed as an honest, unedited record of real
usage — "we log every call we make." Backtest verdicts are real Claude
output but on a synthetic historical prompt, generated by a script rather
than a user asking a question. Writing them to the same table would make
that marketing claim false the moment anyone checked the row count. This
table exists to answer a different, equally legitimate question — "how
good are these verdicts, validated against much more history than real
usage alone could ever produce" — and is presented that way, never merged
into the live ledger.

Resolution reuses core.track_record's price-lookup and return/alpha
calculation as-is: a backtest call is just a call whose date happens to
already be in the past, so every horizon typically resolves on first read
instead of waiting weeks.
"""

from __future__ import annotations

import logging
from datetime import date
from typing import Any

from core.track_record import HORIZONS, _resolve_row

_log = logging.getLogger("stockbrook")

_DUPLICATE_KEY = "23505"


def _supabase():
    try:
        from core.db import get_client
        return get_client()
    except Exception:
        return None


def already_tried(symbol: str, action: str, call_date: date) -> bool:
    """Has this exact (symbol, action, date) combination already been
    generated? Checked before spending an API call, not relied on as the
    only guard — the table's own unique constraint is the real backstop."""
    sb = _supabase()
    if not sb:
        return False
    try:
        res = (sb.table("ai_calls_backtest").select("id")
               .eq("symbol", symbol.upper()).eq("action", action)
               .eq("call_date", call_date.isoformat()).limit(1).execute())
        return bool(res.data)
    except Exception:
        _log.exception("ai_calls_backtest existence check failed for %s %s %s",
                       symbol, action, call_date)
        return False


def log_backtest_call(symbol: str, action: str, decision: str,
                      price_at_call: float | None, spy_at_call: float | None,
                      rules_met: int | None, rules_total: int | None,
                      call_date: date, data_gaps: list[str],
                      filing_form: str | None = None,
                      filing_date: str | None = None) -> bool:
    """Insert one backtest verdict. Returns True on success, False on a
    genuine failure (duplicates are treated as success — the row already
    exists, which is the desired end state either way)."""
    sb = _supabase()
    if not sb:
        _log.error("ai_calls_backtest insert skipped: no Supabase client "
                   "(set SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY)")
        return False
    row = {
        "symbol": symbol.upper(), "action": action, "decision": decision,
        "price_at_call": price_at_call, "spy_at_call": spy_at_call,
        "rules_met": rules_met, "rules_total": rules_total,
        "call_date": call_date.isoformat(), "data_gaps": data_gaps,
        "filing_form": filing_form, "filing_date": filing_date,
    }
    try:
        sb.table("ai_calls_backtest").insert(row).execute()
        return True
    except Exception as exc:
        if getattr(exc, "code", None) == _DUPLICATE_KEY:
            return True
        _log.exception("ai_calls_backtest insert failed for %s %s %s",
                       symbol, action, call_date)
        return False


def _all_backtest_calls() -> list[dict]:
    sb = _supabase()
    if not sb:
        return []
    try:
        res = (sb.table("ai_calls_backtest").select("*")
               .order("created_at", desc=True).limit(10_000).execute())
        return res.data or []
    except Exception:
        _log.exception("ai_calls_backtest read failed")
        return []


def compute_backtest_record() -> dict:
    """Same shape as core.track_record.compute_track_record(), computed
    over the backtest table instead — kept as a distinctly-labeled result
    rather than merged into the live summary."""
    calls = [c for c in _all_backtest_calls() if c.get("decision") == "YES"]
    resolved = [_resolve_row(c) for c in calls]

    summary: dict[str, Any] = {}
    for label in HORIZONS:
        for action in ("buy", "sell"):
            rows = [r for r in resolved if r["action"] == action and f"return_{label}" in r]
            rets = [r[f"return_{label}"] for r in rows]
            alphas = [r[f"alpha_{label}"] for r in rows if f"alpha_{label}" in r]
            wins = sum(1 for r in rets if (r > 0 if action == "buy" else r < 0))
            summary[f"{action}_{label}"] = {
                "count": len(rets),
                "avg_return": round(sum(rets) / len(rets), 4) if rets else None,
                "win_rate": round(wins / len(rets), 4) if rets else None,
                "avg_alpha_vs_spy": round(sum(alphas) / len(alphas), 4) if alphas else None,
            }

    return {
        "summary": summary,
        "total_backtest_calls": len(calls),
        "is_backtest": True,  # every consumer of this dict must label it as such
        "recent_calls": resolved[:60],
    }
