"""
Storage for the AI backtest ledger — verdicts generated on reconstructed
historical dates (core/point_in_time.py), kept in `ai_calls_backtest`,
deliberately separate from the live `ai_calls` table.

Why separate: `ai_calls` is marketed as an honest, unedited record of real
usage — "we log every call we make." Backtest verdicts are real Claude
output but on a synthetic historical prompt, generated by a script rather
than a user asking a question. Writing them to the same table would make
that marketing claim false the moment anyone checked the row count. This
table exists to answer a different, equally legitimate question — "how
good are these verdicts, validated against much more history than real
usage alone could ever produce" — and is presented that way, never merged
into the live ledger.

Resolution reuses core.track_record's price-lookup and return/alpha
calculation as-is: a backtest call is just a call whose date happens to
already be in the past, so every horizon typically resolves on first read
instead of waiting weeks.
"""

from __future__ import annotations

import logging
from datetime import date
from typing import Any

from core.track_record import HORIZONS, _resolve_row

_log = logging.getLogger("stockbrook")

_DUPLICATE_KEY = "23505"


def _supabase():
    try:
        from core.db import get_client
        return get_client()
    except Exception:
        return None


_REQUIRED_COLUMNS = ("criteria_passed", "unsourced_numbers",
                     "response_text", "universe_tier")


def schema_ready() -> bool:
    """Does the table have every column log_backtest_call writes?

    Run before a batch spends anything. A missing column doesn't fail
    until the insert, AFTER the Claude call it was meant to record has
    already been paid for — a whole scheduled run could be spent that way
    with nothing to show for it."""
    sb = _supabase()
    if not sb:
        return False
    try:
        sb.table("ai_calls_backtest").select(",".join(_REQUIRED_COLUMNS)).limit(1).execute()
        return True
    except Exception:
        _log.exception("ai_calls_backtest schema check failed")
        return False


def already_tried(symbol: str, action: str, call_date: date) -> bool:
    """Has this exact (symbol, action, date) combination already been
    generated? Checked before spending an API call, not relied on as the
    only guard — the table's own unique constraint is the real backstop."""
    sb = _supabase()
    if not sb:
        return False
    try:
        res = (sb.table("ai_calls_backtest").select("id")
               .eq("symbol", symbol.upper()).eq("action", action)
               .eq("call_date", call_date.isoformat()).limit(1).execute())
        return bool(res.data)
    except Exception:
        _log.exception("ai_calls_backtest existence check failed for %s %s %s",
                       symbol, action, call_date)
        return False


def log_backtest_call(symbol: str, action: str, decision: str,
                      price_at_call: float | None, spy_at_call: float | None,
                      rules_met: int | None, rules_total: int | None,
                      call_date: date, data_gaps: list[str],
                      filing_form: str | None = None,
                      filing_date: str | None = None,
                      criteria_passed: bool | None = None,
                      unsourced: list[str] | None = None,
                      response_text: str | None = None,
                      universe_tier: str | None = None) -> bool:
    """Insert one backtest verdict. Returns True on success, False on a
    genuine failure (duplicates are treated as success — the row already
    exists, which is the desired end state either way)."""
    sb = _supabase()
    if not sb:
        _log.error("ai_calls_backtest insert skipped: no Supabase client "
                   "(set SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY)")
        return False
    row = {
        "symbol": symbol.upper(), "action": action, "decision": decision,
        "price_at_call": price_at_call, "spy_at_call": spy_at_call,
        "rules_met": rules_met, "rules_total": rules_total,
        "call_date": call_date.isoformat(), "data_gaps": data_gaps,
        "filing_form": filing_form, "filing_date": filing_date,
        "criteria_passed": criteria_passed,
        # None stays None: that's "not audited", which the faithfulness
        # rate must exclude rather than count as a clean result. An empty
        # list is the different, stronger claim that it WAS audited and
        # nothing was flagged.
        "unsourced_numbers": unsourced,
        # Kept so a flagged number can be read in context later. Without
        # the model's own words, "unsourced" can't be told apart from
        # honest arithmetic after the fact.
        "response_text": response_text,
        "universe_tier": universe_tier,
    }
    try:
        sb.table("ai_calls_backtest").insert(row).execute()
        return True
    except Exception as exc:
        if getattr(exc, "code", None) == _DUPLICATE_KEY:
            return True
        _log.exception("ai_calls_backtest insert failed for %s %s %s",
                       symbol, action, call_date)
        return False


def _all_backtest_calls() -> list[dict]:
    sb = _supabase()
    if not sb:
        return []
    # Paged, not one .limit(): Supabase caps a single response at 1,000 rows
    # regardless of the limit asked for, so a lone request silently returns
    # the newest 1,000 and every total computed from it stops growing.
    rows: list[dict] = []
    page = 1000
    try:
        while True:
            res = (sb.table("ai_calls_backtest").select("*")
                   .order("id", desc=True)
                   .range(len(rows), len(rows) + page - 1).execute())
            batch = res.data or []
            rows.extend(batch)
            if len(batch) < page:
                return rows
    except Exception:
        # Not the pages read so far — a partial set is exactly the silent
        # undercount the paging exists to prevent.
        _log.exception("ai_calls_backtest read failed")
        return []


def _score(rows: list[dict], action: str, label: str) -> dict:
    """Win rate / return / alpha for one set of already-resolved calls.

    Both returns and alpha are reported in the DIRECTION THE CALL IMPLIED,
    not as the raw stock move: for a sell, a stock that fell is a win, so
    its sign is flipped here. The raw per-row `return_*`/`alpha_*` fields
    stay factual (what the stock actually did) — this is the only place
    that reorients them, because an aggregate labelled "avg alpha" is
    read as "how well did the calls do", and an unflipped sell average
    says the exact opposite of what a reader assumes.
    """
    rows = [r for r in rows if f"return_{label}" in r]
    if not rows:
        return {"count": 0, "avg_return": None, "win_rate": None,
                "avg_alpha_vs_spy": None}
    sign = 1 if action == "buy" else -1
    rets = [sign * r[f"return_{label}"] for r in rows]
    alphas = [sign * r[f"alpha_{label}"] for r in rows if f"alpha_{label}" in r]
    wins = sum(1 for r in rets if r > 0)
    return {
        "count": len(rets),
        "avg_return": round(sum(rets) / len(rets), 4),
        "win_rate": round(wins / len(rets), 4),
        "avg_alpha_vs_spy": round(sum(alphas) / len(alphas), 4) if alphas else None,
    }


def _summarize(resolved: list[dict]) -> dict[str, Any]:
    ai_yes = [r for r in resolved if r.get("decision") == "YES"]
    rules_passed = [r for r in resolved if r.get("criteria_passed") is True]
    summary: dict[str, Any] = {}
    for label in HORIZONS:
        for action in ("buy", "sell"):
            def by_action(rows: list[dict]) -> list[dict]:
                return [r for r in rows if r["action"] == action]
            summary[f"{action}_{label}"] = {
                "ai_yes": _score(by_action(ai_yes), action, label),
                "rules_passed": _score(by_action(rules_passed), action, label),
                "all_calls": _score(by_action(resolved), action, label),
            }
    return summary


def compute_backtest_record() -> dict:
    """Scored backtest results, as three arms that only mean something
    side by side.

      ai_yes        — calls where Claude said YES
      rules_passed  — calls where the deterministic criteria passed,
                      whatever Claude then said
      all_calls     — every call sampled, the base rate

    The third arm is what makes the other two readable. Equities drift
    up, so on a long horizon a "sell" that never fires looks brilliant
    and one that always fires looks terrible, with no skill involved
    either way. A win rate is only interpretable as the distance between
    an arm and that base rate — and the AI is only earning its cost if
    ai_yes beats rules_passed, since the rules run for free.

    Also split by the universe tier each call was sampled from. The first
    ~800 calls came from a fixed list of 30 mega-caps (recorded as
    "legacy30"), which are large today because they rose — a finding that
    only shows up there may be that bias rather than the model.
    """
    all_rows = _all_backtest_calls()
    resolved = [_resolve_row(c) for c in all_rows]

    tiers = sorted({r.get("universe_tier") or "unknown" for r in resolved})
    by_tier = {
        t: {
            "calls": sum(1 for r in resolved if (r.get("universe_tier") or "unknown") == t),
            "summary": _summarize([r for r in resolved
                                   if (r.get("universe_tier") or "unknown") == t]),
        }
        for t in tiers
    }

    # Rows written before criteria_passed/unsourced_numbers existed carry
    # NULLs; the comparison arms are only as big as the rows that have them.
    with_baseline = sum(1 for r in all_rows if r.get("criteria_passed") is not None)
    audited = [r for r in all_rows if r.get("unsourced_numbers") is not None]
    flagged = [r for r in audited if r.get("unsourced_numbers")]

    return {
        "summary": _summarize(resolved),
        "by_tier": by_tier,
        "total_backtest_calls": len(all_rows),
        "ai_yes_calls": sum(1 for r in resolved if r.get("decision") == "YES"),
        "rows_with_baseline": with_baseline,
        "faithfulness": {
            "audited": len(audited),
            "with_unsourced_numbers": len(flagged),
            "rate": round(len(flagged) / len(audited), 4) if audited else None,
        },
        "is_backtest": True,  # every consumer of this dict must label it as such
        "recent_calls": resolved[:60],
    }
